# Generated by Django 4.2.6 on 2023-10-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
