# Generated by Django 4.2.6 on 2023-10-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('article', '0004_remove_article_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField()),
                ('field_1_name', models.CharField(max_length=255)),
                ('field_1_value', models.CharField(max_length=255, null=True)),
                ('corresponding_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='contenttypes.contenttype')),
            ],
        ),
    ]
