# Generated by Django 4.2.6 on 2023-10-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_additionalcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1_name', models.CharField(max_length=255)),
                ('field_1_value', models.CharField(max_length=255)),
                ('field_2_name', models.CharField(max_length=255)),
                ('field_2_value', models.CharField(max_length=255)),
                ('field_3_name', models.CharField(max_length=255)),
                ('field_3_value', models.CharField(max_length=255)),
                ('field_4_name', models.CharField(max_length=255)),
                ('field_4_value', models.CharField(max_length=255)),
                ('field_5_name', models.CharField(max_length=255)),
                ('field_5_value', models.CharField(max_length=255)),
                ('field_6_name', models.CharField(max_length=255)),
                ('field_6_value', models.CharField(max_length=255)),
                ('field_7_name', models.CharField(max_length=255)),
                ('field_7_value', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalColumn',
        ),
    ]
