# Generated by Django 4.2.6 on 2023-10-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articleadditionalfield_delete_additionalcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdditionalColum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='articleadditionalfield',
            old_name='article',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='articleadditionalfield',
            old_name='field_1_name',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_1_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_2_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_2_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_3_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_3_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_4_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_4_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_5_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_5_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_6_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_6_value',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_7_name',
        ),
        migrations.RemoveField(
            model_name='articleadditionalfield',
            name='field_7_value',
        ),
        migrations.AddField(
            model_name='articleadditionalfield',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.articleadditionalcolum'),
            preserve_default=False,
        ),
    ]
