# Generated by Django 4.2.6 on 2023-10-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articleadditionalcolum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleAdditionalColum',
            new_name='ArticleAdditionalColumn',
        ),
    ]
